apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helpers.fullName" . }}
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helpers.selectorLabels" . | nindent 6 }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helpers.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helpers.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          command: {{ .Values.image.command }}
          args: {{ .Values.image.args }}
          {{- if .Values.envFrom }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.cloudContext.enabled }}
            # GoWish Cloud Context environment variables
            - name: GWCC_PROVIDER
              value: {{ .Values.cloudContext.provider | quote }}
            {{- if .Values.cloudContext.region }}
            - name: GWCC_REGION
              value: {{ .Values.cloudContext.region | quote }}
            {{- end }}
            {{- if .Values.cloudContext.regionGroup }}
            - name: GWCC_REGION_GROUP
              value: {{ .Values.cloudContext.regionGroup | quote }}
            {{- end }}
            {{- if .Values.cloudContext.zone }}
            - name: GWCC_ZONE
              value: {{ .Values.cloudContext.zone | quote }}
            {{- end }}
            {{- if .Values.cloudContext.clusterName }}
            - name: GWCC_CLUSTER_NAME
              value: {{ .Values.cloudContext.clusterName | quote }}
            {{- end }}
            - name: GWCC_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GWCC_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- end }}
            {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
        {{- if .Values.sidecars }}
        {{- toYaml .Values.sidecars | nindent 8 }}
        {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range . }}
        - maxSkew:
            {{- if $.Values.defaultTopologySpreadConstraints }}
            {{ default $.Values.defaultTopologySpreadConstraints.maxSkew .maxSkew }}
            {{- else }}
            {{ .maxSkew | default 1 }}
            {{- end }}
          topologyKey: {{ required "topologyKey is required!" .topologyKey }}
          whenUnsatisfiable:
            {{- if $.Values.defaultTopologySpreadConstraints }}
            {{ default $.Values.defaultTopologySpreadConstraints.whenUnsatisfiable .whenUnsatisfiable }}
            {{- else }}
            {{ .whenUnsatisfiable | default "DoNotSchedule" }}
            {{- end }}
          labelSelector:
            matchLabels:
              {{- include "helpers.selectorLabels" $ | nindent 16 }}
              {{- with .additionalLabels }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
