{{- if .Values.cronJobs.enabled }}
{{- range .Values.cronJobs.list }}
---
apiVersion: {{ .apiVersion | default $.Values.cronJobs.apiVersion }}
kind: CronJob
metadata:
  name: {{ .name }}
  {{- if .metadata }}
  {{- with .metadata }}
  {{- omit . "name" | toYaml | nindent 2 }}
  {{- end }}
  {{- end }}
spec:
  schedule: {{ .schedule | quote }}
  {{- if .concurrencyPolicy }}
  concurrencyPolicy: {{ .concurrencyPolicy }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          {{- toYaml .containers | nindent 12 }}
          {{- if .restartPolicy }}
          restartPolicy: {{ .restartPolicy }}
          {{- end }}
          {{- if .activeDeadlineSeconds }}
          activeDeadlineSeconds: {{ .activeDeadlineSeconds }}
          {{- end }}
          {{- with .additionalSpec }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
  {{- with .additionalJobSpec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}