{{- if .Values.healthCheckPolicy.enabled -}}
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ include "helpers.serviceName" . }}-healthcheck
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
spec:
  # default applies to all backends of this Service
  default:
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_NAMED_PORT
        portName: {{ include "helpers.portName" . }}
        requestPath: {{ .Values.healthCheckPolicy.httpHealthCheck.requestPath }}
    checkIntervalSec: {{ .Values.healthCheckPolicy.checkIntervalSec }}
    timeoutSec: {{ .Values.healthCheckPolicy.timeoutSec }}
    healthyThreshold: {{ .Values.healthCheckPolicy.healthyThreshold }}
    unhealthyThreshold: {{ .Values.healthCheckPolicy.unhealthyThreshold }}
  targetRef:
    {{- if .Values.serviceExport.enabled }}
    group: "net.gke.io"
    kind: ServiceImport
    {{- else }}
    group: ""
    kind: "Service"
    {{- end }}
    name: {{ include "helpers.serviceName" . }}
{{- end }}
