## m,irror the httproute from store demo into a chartm, it should be the same
{{- /*
A simple template that emits an HTTPRoute when .Values.httpRoute.enabled is true.
Hard-coded defaults fall back to your current values file.
*/ -}}
{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "helpers.fullName" . }}-http-route
  namespace: {{ .Values.httpRoute.namespace | default .Release.Namespace }}
  labels:
    gateway: {{ .Values.httpRoute.gatewayName }}
spec:
  parentRefs:
    - kind: Gateway
      namespace: {{ .Values.httpRoute.gatewayNamespace }}
      name: {{ .Values.httpRoute.gatewayName  }} 
  hostnames:
    - {{ .Values.httpRoute.hostname | quote }}
  rules:
    - backendRefs:
      - group: net.gke.io
        kind: ServiceImport
        name: {{ .Release.Name }}-{{ .Values.nameOverride }} 
        namespace: {{ .Values.httpRoute.namespace | default .Release.Namespace }}
        port: {{ .Values.containerPort }}
{{- end }}

