{{- if .Values.httpRoute.enabled | default false }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "helpers.fullName" . }}
  labels:
    gateway: {{ .Values.httpRoute.gatewayName }}
spec:
  parentRefs:
    - kind: Gateway
      namespace: {{ .Values.httpRoute.gatewayNamespace }}
      name: {{ .Values.httpRoute.gatewayName  }} 
  hostnames:
    - {{ .Values.httpRoute.hostname | quote }}
  rules:
    - backendRefs:
      - group: net.gke.io
        kind: ServiceImport
        name: {{ include "helpers.fullName" . }}
        port: {{ .Values.service.port }}
{{- end }}

