{{- if .Values.httpRoute.enabled | default false }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "helpers.fullName" . }}
  labels:
    gateway: {{ .Values.httpRoute.gatewayName }}
spec:
  parentRefs:
    - kind: Gateway
      namespace: {{ .Values.httpRoute.gatewayNamespace }}
      name: {{ .Values.httpRoute.gatewayName  }} 
  hostnames:
    - {{ .Values.httpRoute.hostname | quote }}
  rules:
    - backendRefs:
      # Default service (backward compatible)
      {{- if and (not .Values.httpRoute.additionalBackends) (not (hasKey .Values.httpRoute "defaultWeight")) }}
      - group: net.gke.io
        kind: ServiceImport
        name: {{ include "helpers.fullName" . }}
        port: {{ .Values.service.port }}
      {{- else }}
      # Default service with weight (new behavior)
      {{- if gt (int (.Values.httpRoute.defaultWeight | default 100)) 0 }}
      - group: net.gke.io
        kind: ServiceImport
        name: {{ include "helpers.fullName" . }}
        port: {{ .Values.service.port }}
        weight: {{ .Values.httpRoute.defaultWeight | default 100 }}
      {{- end }}
      # Additional backends
      {{- range .Values.httpRoute.additionalBackends }}
      {{- if gt (int .weight) 0 }}
      - group: net.gke.io
        kind: ServiceImport
        name: {{ .name }}
        port: {{ $.Values.service.port }}
        weight: {{ .weight }}
      {{- end }}
      {{- end }}
      {{- end }}
{{- end }}
