{{- $root := . -}}
{{- if .Values.infisicalSecretCRD.enabled }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ include "helpers.fullName" . }}
spec:
  hostAPI: "https://env.gowish.com/api"
  resyncInterval: {{ .Values.infisicalSecretCRD.resyncInterval | default 60 }}
  authentication:
    universalAuth:
      credentialsRef:
        secretName: {{ .Values.infisicalSecretCRD.authentication.universalAuth.credentialsRef.secretName | quote }}
        secretNamespace: {{ .Values.infisicalSecretCRD.authentication.universalAuth.credentialsRef.secretNamespace | default $root.Release.Namespace | quote }}
      secretsScope:
        envSlug: {{ .Values.infisicalSecretCRD.authentication.universalAuth.secretsScope.envSlug | quote }}
        projectSlug: {{ .Values.infisicalSecretCRD.authentication.universalAuth.secretsScope.projectSlug | quote }}
        secretsPath: "/"  # You can also make this configurable if desired.
  managedKubeSecretReferences:
    {{- /* Save the parent context in $root to retain access to .Release.Namespace in the range block */ -}}
    {{- range .Values.infisicalSecretCRD.managedKubeSecretReferences }}
    - secretName: {{ .secretName | quote }}
      secretNamespace: {{ .secretNamespace | default $root.Values.infisicalSecretCRD.secretNamespace | default $root.Release.Namespace | quote }}
    {{- end }}
  creationPolicy: "Orphan"
{{- end }}
