{{- if .Values.jobs.enabled }}
{{- range .Values.jobs.list }}
---
apiVersion: {{ .apiVersion | default $.Values.jobs.apiVersion }}
kind: Job
metadata:
  name: {{ .name }}
  {{- if .metadata }}
  {{- with .metadata }}
  {{- omit . "name" | toYaml | nindent 2 }}
  {{- end }}
  {{- end }}
spec:
  template:
    spec:
      containers:
      {{- toYaml .containers | nindent 8 }}
      {{- if .restartPolicy }}
      restartPolicy: {{ .restartPolicy }}
      {{- end }}
      {{- if .activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ .activeDeadlineSeconds }}
      {{- end }}
      {{- with .additionalSpec }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  {{- with .additionalJobSpec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
