{{- if .Values.jobs.enabled }}
{{- range .Values.jobs.list }}
---
apiVersion: {{ .apiVersion | default $.Values.jobs.apiVersion }}
kind: {{ .kind | default $.Values.jobs.kind }}
metadata:
  name: {{ .name }}
  {{- if .metadata }}
  {{- with .metadata }}
  {{- omit . "name" | toYaml | nindent 2 }}
  {{- end }}
  {{- end }}
spec:
  {{- if eq (default $.Values.jobs.kind .kind) "CronJob" }}
  schedule: {{ .schedule | quote }}
  {{- if .concurrencyPolicy }}
  concurrencyPolicy: {{ .concurrencyPolicy }}
  {{- end }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          {{- toYaml .containers | nindent 12 }}
          {{- if .restartPolicy }}
          restartPolicy: {{ .restartPolicy }}
          {{- end }}
          {{- if .activeDeadlineSeconds }}
          activeDeadlineSeconds: {{ .activeDeadlineSeconds }}
          {{- end }}
          {{- with .additionalSpec }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
  {{- else }}
  template:
    spec:
      containers:
      {{- toYaml .containers | nindent 8 }}
      {{- if .restartPolicy }}
      restartPolicy: {{ .restartPolicy }}
      {{- end }}
      {{- if .activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ .activeDeadlineSeconds }}
      {{- end }}
      {{- with .additionalSpec }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  {{- end }}
  {{- with .additionalJobSpec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
