{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "helpers.fullName" . }}-network-policy
spec:
  podSelector:
    matchLabels:
      {{- include "helpers.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- range .Values.networkPolicy.policyTypes }}
    - {{ . }}
    {{- end }}

  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- range .Values.networkPolicy.ingress }}
    - from:
        {{- if .ipBlock }}
        - ipBlock:
            cidr: {{ .ipBlock.cidr | quote }}
            {{- if .ipBlock.except }}
            except:
              {{- range .ipBlock.except }}
              - {{ . | quote }}
              {{- end }}
            {{- end }}
        {{- end }}
        {{- if .namespaceSelector }}
        - namespaceSelector:
            matchLabels:
              {{- toYaml .namespaceSelector.matchLabels | nindent 14 }}
        {{- end }}
        {{- if .podSelector }}
        - podSelector:
            matchLabels:
              {{- toYaml .podSelector.matchLabels | nindent 14 }}
        {{- end }}
    {{- end }}
  {{- end }}

  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- range .Values.networkPolicy.egress }}
    - to:
        {{- if .ipBlock }}
        - ipBlock:
            cidr: {{ .ipBlock.cidr | quote }}
            {{- if .ipBlock.except }}
            except:
              {{- range .ipBlock.except }}
              - {{ . | quote }}
              {{- end }}
            {{- end }}
        {{- end }}
        {{- if .namespaceSelector }}
        - namespaceSelector:
            matchLabels:
              {{- toYaml .namespaceSelector.matchLabels | nindent 14 }}
        {{- end }}
        {{- if .podSelector }}
        - podSelector:
            matchLabels:
              {{- toYaml .podSelector.matchLabels | nindent 14 }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
