{{- if .Values.serviceExport.enabled }}
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
  name: {{ include "helpers.serviceName" . }}
  {{- if .Values.serviceExport.annotations }}
  annotations:
    {{- toYaml .Values.serviceExport.annotations | nindent 4 }}
  {{- end }}
{{- end }}
